# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=48)),
                ('last_name', models.CharField(max_length=48)),
                ('date_of_birth', models.DateTimeField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=48)),
                ('state', models.CharField(max_length=48)),
                ('med_notes', models.CharField(max_length=400)),
                ('church', models.CharField(max_length=100)),
                ('pastor', models.CharField(max_length=100)),
                ('church_member', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
