# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='paypal',
            field=models.CharField(default='earlier', max_length=48),
        ),
        migrations.AlterField(
            model_name='camper',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
