# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190303_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='paypal',
            field=models.CharField(default='untouched', max_length=48),
        ),
    ]
