# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-07-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190303_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
