# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-07-08 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200708_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camper',
            old_name='timestamp',
            new_name='created',
        ),
    ]
