# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-07-08 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200708_0626'),
    ]

    def add_camp_filter(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Camper = apps.get_model('registration', 'Camper')
        for c in Camper.objects.all():
            if c.created.year == 2020:
                c.camp_filter = "spring camp 2020"
            else:
                c.camp_filter = "camp 2019"
            c.save()

    operations = [
        migrations.AddField(
            model_name='camper',
            name='camp_filter',
            field=models.CharField(default='not caught', max_length=48),
        ),
        migrations.RunPython(add_camp_filter),
    ]


