# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-06-09 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_camper_camp_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='pastor_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
