# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2023-04-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_camper_pastor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='not_married',
            field=models.BooleanField(default=False),
        ),
    ]
