# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2025-04-03 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_camper_not_married'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='swshirt_size',
            field=models.CharField(choices=[('None', 'None'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='None', help_text="Select the swim shirt size for the camper. 'None' means no swim shirt is needed.", max_length=4, verbose_name='Swim Shirt Size'),
        ),
        migrations.AddField(
            model_name='camper',
            name='tshirt_size',
            field=models.CharField(choices=[('None', 'None'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], default='None', help_text="Select the t-shirt size for the camper. 'None' means no t-shirt is needed.", max_length=4, verbose_name='T-shirt Size'),
        ),
    ]
