# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2025-04-16 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20250415_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
