# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2025-07-30 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_camper_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='swshirt_size',
            field=models.CharField(choices=[('None', 'None'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('3XL', '3 Extra Large')], default='None', help_text="Select the swim shirt size for the camper. 'None' means no swim shirt is needed.", max_length=4, null=True, verbose_name='Swim Shirt Size'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='tshirt_size',
            field=models.CharField(choices=[('None', 'None'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('3XL', '3 Extra Large'), ('4XL', '4 Extra Large'), ('5XL', '5 Extra Large')], default='None', help_text="Select the t-shirt size for the camper. 'None' means no t-shirt is needed.", max_length=4, null=True, verbose_name='T-shirt Size'),
        ),
    ]
