# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2025-12-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20250730_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='activity',
            field=models.CharField(choices=[('ski', 'Ski/Snowboard'), ('tub', 'Tubing'), ('stay', 'Stay at the Cabin')], default='None', help_text="Select the t-shirt size for the camper. 'None' means no t-shirt is needed.", max_length=4, null=True, verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='camper',
            name='region',
            field=models.CharField(choices=[('oregon', 'Oregon Region'), ('seattle', 'Seattle Region'), ('spokane', 'Spokane Region')], default='None', help_text="Select the t-shirt size for the camper. 'None' means no t-shirt is needed.", max_length=4, null=True, verbose_name='Activity'),
        ),
    ]
