# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2025-12-06 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20251206_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='region',
            field=models.CharField(choices=[('oregon', 'Oregon Region'), ('seattle', 'Seattle Region'), ('spokane', 'Spokane Region')], default='None', help_text="Select the t-shirt size for the camper. 'None' means no t-shirt is needed.", max_length=8, null=True, verbose_name='Activity'),
        ),
    ]
