# Generated by Django 4.2 on 2026-06-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20251206_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
