# Generated by Django 4.2 on 2026-06-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20251206_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='camper',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='None', help_text="Select the gender. 'None' means legacy campers.", max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='swshirt_size',
            field=models.CharField(choices=[('None', 'None'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('3XL', '3 Extra Large')], default='None', help_text="Select the sweat shirt size for the camper. 'None' means no sweat shirt is needed.", max_length=4, null=True, verbose_name='Sweat Shirt Size'),
        ),
    ]
