# Generated by Django 4.2 on 2026-06-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_camper_gender_alter_camper_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='swshirt_size',
            field=models.CharField(choices=[('None', 'None'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('3XL', '3 Extra Large'), ('4XL', '4 Extra Large'), ('5XL', '5 Extra Large')], default='None', help_text="Select the sweat shirt size for the camper. 'None' means no sweat shirt is needed.", max_length=4, null=True, verbose_name='Sweat Shirt Size'),
        ),
    ]
