# Generated by Django 5.2.16 on 2026-08-04 05:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def truncate_date_of_birth(apps, schema_editor):
    """Drop the time component from stored dates of birth, on SQLite only.

    SQLite has no real date type, so the existing DateTimeField values are text
    with a trailing " 00:00:00" that a DateField cannot read back. Other
    backends convert the column properly during the ALTER and need no help.
    """
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE registration_camper "
            "SET date_of_birth = substr(date_of_birth, 1, 10) "
            "WHERE date_of_birth IS NOT NULL AND length(date_of_birth) > 10"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_camper_gender_alter_camper_swshirt_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL key, for example 'summer-2026'.", max_length=40, unique=True)),
                ('name', models.CharField(help_text="Display name, for example 'Fully Alive Retreat 2026'.", max_length=120)),
                ('legacy_filter_key', models.CharField(help_text='The value stored in Camper.camp_filter for this season. Do not change this on an existing season; historical records match on it.', max_length=48, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='The season the public site shows. Exactly one may be active.')),
                ('registration_open', models.BooleanField(default=False, help_text='Uncheck to close registration immediately.')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=150)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('330.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('merch_enabled', models.BooleanField(default=True)),
                ('merch_deadline', models.DateTimeField(blank=True, help_text='After this moment merchandise can no longer be ordered.', null=True)),
                ('hoodie_price', models.DecimalField(decimal_places=2, default=Decimal('45.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mug_enabled', models.BooleanField(default=False)),
                ('mug_price', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, default='Twin Rocks Camp', max_length=120)),
                ('venue_address', models.CharField(blank=True, default='18705 N Hwy 101, Rockaway Beach, OR 97136', max_length=200)),
                ('venue_url', models.URLField(blank=True, default='http://www.twinrocks.org')),
                ('min_age', models.PositiveSmallIntegerField(default=23, help_text='Youngest age admitted, measured on the first day of camp.')),
                ('max_age', models.PositiveSmallIntegerField(default=45, help_text='Campers at or above this age are directed to the age notice.')),
                ('paypal_item_name', models.CharField(blank=True, help_text='Line item shown on the PayPal receipt. Defaults to the season name.', max_length=127)),
                ('theme', models.CharField(choices=[('summer', 'Summer / coast'), ('winter', 'Winter')], default='summer', max_length=10)),
                ('registration_deadline_note', models.CharField(blank=True, help_text="Free text shown on the info page, for example 'August 16th'.", max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'camp season',
                'verbose_name_plural': 'camp seasons',
                'ordering': ('-starts_at', '-id'),
            },
        ),
        migrations.AlterModelOptions(
            name='camper',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='camper',
            name='paypal',
        ),
        migrations.AddField(
            model_name='camper',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='camper',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross amount PayPal reported. Set by the IPN handler.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='camper',
            name='payment_flagged',
            field=models.BooleanField(default=False, help_text='A payment arrived that did not match the expected amount or receiver.'),
        ),
        migrations.AddField(
            model_name='camper',
            name='payment_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='camper',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('rejected_married', 'Not eligible (married / not a church member)'), ('rejected_age', 'Not eligible (age)')], db_index=True, default='registered', max_length=20),
        ),
        migrations.AddField(
            model_name='camper',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='activity',
            field=models.CharField(blank=True, choices=[('ski', 'Ski / snowboard'), ('tub', 'Tubing'), ('stay', 'Stay at the cabin')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='camp_filter',
            field=models.CharField(default='not caught', editable=False, max_length=48),
        ),
        migrations.AlterField(
            model_name='camper',
            name='church_member',
            field=models.BooleanField(default=False),
        ),
        # date_of_birth is becoming a DateField. On SQLite the values are stored
        # as text like "1990-04-12 00:00:00"; the column type changes but the
        # text does not, and the DateField converter then fails to parse it and
        # silently yields None. Truncate to the date part first.
        # Postgres needs nothing here: ALTER TYPE date casts the timestamp.
        migrations.RunPython(
            truncate_date_of_birth, migrations.RunPython.noop, elidable=False
        ),
        migrations.AlterField(
            model_name='camper',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='camper',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='camper',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default=None, help_text='Blank on legacy campers registered before this field existed.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='med_notes',
            field=models.CharField(blank=True, default='', help_text='Allergies, conditions or medication we should know about.', max_length=400, verbose_name='Medical notes'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='camper',
            name='pastor_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a phone number, for example 509-555-0123.', regex='^[0-9+().\\-\\s]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='camper',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a phone number, for example 509-555-0123.', regex='^[0-9+().\\-\\s]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='camper',
            name='region',
            field=models.CharField(blank=True, choices=[('oregon', 'Oregon'), ('seattle', 'Seattle'), ('spokane', 'Spokane')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='camper',
            name='swshirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('3XL', '3X Large'), ('4XL', '4X Large'), ('5XL', '5X Large')], default=None, help_text='Blank means none ordered.', max_length=4, null=True, verbose_name='Forest hoodie size'),
        ),
        migrations.AlterField(
            model_name='camper',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2X Large'), ('3XL', '3X Large'), ('4XL', '4X Large'), ('5XL', '5X Large')], default=None, help_text='Blank means none ordered.', max_length=4, null=True, verbose_name='Sage hoodie size'),
        ),
        migrations.AddField(
            model_name='camper',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campers', to='registration.campseason'),
        ),
        migrations.AddIndex(
            model_name='camper',
            index=models.Index(fields=['season', 'paid'], name='registratio_season__9aa34e_idx'),
        ),
        migrations.AddIndex(
            model_name='camper',
            index=models.Index(fields=['camp_filter', 'paid'], name='registratio_camp_fi_64d01d_idx'),
        ),
        migrations.AddIndex(
            model_name='camper',
            index=models.Index(fields=['email'], name='registratio_email_4d5a11_idx'),
        ),
    ]
