# Generated by Django 4.2 on 2026-06-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_camper_id'),
        ('registration', '0015_alter_camper_swshirt_size'),
    ]

    operations = [
    ]
